package com.company.base.endpoint.event.model;

import com.company.base.PojaGenerated;
import java.io.Serializable;

/**
 * Event models generated by EventBridge are NOT typed, unfortunately. TypedEvent takes care of
 * that.
 */
@PojaGenerated
public interface TypedEvent {
  String getTypeName();

  Serializable getPayload();
}
